version: '3'

services:
    # reverseproxy:
    #     image: reverseproxy
    #     ports:
    #         - 8080:8080
    #     restart: always
    #     depends_on:
    #         - backend
    backend:
        build: .
        image: nairuby-api
        restart: always
        environment:
            - RAILS_ENV=production
            - DBHOST=$DBHOST
            - DBUSER=$DBUSER
            - DBPASS=$DBUSER
        ports:
            - 3000:3000
